name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build and Test with Gradle
      run: ./gradlew clean test --rerun-tasks
      env:
        REAI_API_KEY: ${{ secrets.API_KEY }}
